### ISSUE TITLE
cannot find -lhdf5

### ISSUE THREAD

**Issue by loretoparisi** [CMU-Perceptual-Computing-Lab/openpose#123]
I get this error:

```
/usr/bin/ld: cannot find -lhdf5_hl
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1
```

This seems to be a well known issue with caffe mentioned in https://github.com/NVIDIA/DIGITS/issues/156

The problem is that I'm using the example `Makefile.config` for `Ubuntu16.04` where the proposed solution is right there:

```
# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/hdf5/serial
```

The headers are actually there:

```
find /usr -iname "*hdf5.h*"
/usr/local/include/opencv2/flann/hdf5.h
/usr/include/hdf5/serial/hdf5.h
```

So I have also manually added

```
apt-get update && apt-get install -y \
    libhdf5-10 \
    libhdf5-serial-dev \
    libhdf5-dev \
    libhdf5-cpp-11
export CPATH="/usr/include/hdf5/serial/"
```

but I still get the same error.

This last approach was suggested [here](https://ahmedibrahimvt.wordpress.com/2017/02/19/fatal-error-hdf5-h-no-such-file-or-directory/)

**Comment by loretoparisi** [comment]
**[UPDATE]**

Checking the so files with `ld -lhdf5 --verbose` I can see

```
==================================================
attempt to open //usr/local/lib/x86_64-linux-gnu/libhdf5.so failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libhdf5.a failed
attempt to open //lib/x86_64-linux-gnu/libhdf5.so failed
attempt to open //lib/x86_64-linux-gnu/libhdf5.a failed
attempt to open //usr/lib/x86_64-linux-gnu/libhdf5.so failed
attempt to open //usr/lib/x86_64-linux-gnu/libhdf5.a failed
attempt to open //usr/local/lib64/libhdf5.so failed
attempt to open //usr/local/lib64/libhdf5.a failed
attempt to open //lib64/libhdf5.so failed
attempt to open //lib64/libhdf5.a failed
attempt to open //usr/lib64/libhdf5.so failed
attempt to open //usr/lib64/libhdf5.a failed
attempt to open //usr/local/lib/libhdf5.so failed
attempt to open //usr/local/lib/libhdf5.a failed
attempt to open //lib/libhdf5.so failed
attempt to open //lib/libhdf5.a failed
attempt to open //usr/lib/libhdf5.so failed
attempt to open //usr/lib/libhdf5.a failed
attempt to open //usr/x86_64-linux-gnu/lib64/libhdf5.so failed
attempt to open //usr/x86_64-linux-gnu/lib64/libhdf5.a failed
attempt to open //usr/x86_64-linux-gnu/lib/libhdf5.so failed
attempt to open //usr/x86_64-linux-gnu/lib/libhdf5.a failed
ld: cannot find -lhdf5
```

so I have fixed my symlink accordingly like

```
cd /usr/lib/x86_64-linux-gnu/hdf5/serial && \
    # lib
    sudo ln -s libhdf5_hl.so /usr/lib/libhdf5_hl.so && \
    sudo ln -s libhdf5.so /usr/lib/libhdf5.so && \
    # lib64
    sudo ln -s libhdf5_hl.so /usr/local/lib/libhdf5_hl.so && \
    sudo ln -s libhdf5.so /usr/local/lib/libhdf5.so
```

but still no luck...

```
/usr/bin/ld: cannot find -lhdf5_hl
/usr/bin/ld: cannot find -lhdf5
/usr/bin/ld: cannot find -lopencv_contrib
```

**Comment by gineshidalgo99** [comment]
Hi, I do not remember how, but you need to manually link them with ldconfig. I do not know why your device did not do it automatically after installing them and reboot...

**Comment by loretoparisi** [comment]
@gineshidalgo99 yes, at the  end in all proposed solutions, there was need to manually link, the strange fact is that I have tried all I knew so far (see above) but with no success.

**Comment by gineshidalgo99** [comment]
Did you reboot the computer after `sudo ln -s` and/or did you do `sudo ldconfig` in all the terminals you were using after that command?

**Comment by loretoparisi** [comment]
@gineshidalgo99 good question. I'm using `docker` so I will try `sudo ldconfig` first.

**Comment by loretoparisi** [comment]
@gineshidalgo99 So I have updated the repo, and I'm using the new install scripts like:

```
# Build OpenPose + Caffe
RUN git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
COPY caffe/Makefile.config openpose/3rdparty/caffe/
COPY caffe/Makefile openpose/3rdparty/caffe/

RUN \
    cd openpose && \
    bash ./ubuntu/install_caffe_and_openpose_if_cuda8.sh
```

getting a `./ubuntu/install_caffe_and_openpose_if_cuda8.sh: ./install_caffe_if_cuda8.sh: /bin/bash: bad interpreter: Text file busy`

**Comment by loretoparisi** [comment]
...fixed that sent a PR also.

**Comment by gineshidalgo99** [comment]
Ups, thanks! I also realized another mistake in the script. Now the script (after your pull request and my last commit) should be working properly.

**Comment by kirubeltadesse** [comment]
I am having the same problem could you please explain how you solved the problem.  I am using Bash On Ubuntu On Windows.

**Comment by lachinaj** [comment]
Replace to Makefile (line: 182)
hdf5_hl hdf5 => hdf5_hl_cpp hdf5_cpp hdf5_serial hdf5_serial_hl

**Comment by kirubeltadesse** [comment]
Thank you but I am still getting error like

LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -l -llmdb
collect2: error: ld returned 1 exit status
Makefile:574: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1

**Comment by salman-ghauri** [comment]
@kirubeltadesse https://stackoverflow.com/questions/39805867/usr-bin-ld-cannot-find-lhdf5-hl This question might help you solve this problem.
